### ISSUE TITLE
request permission to use your project

### ISSUE THREAD

**Issue by ZeroCool00** [ozgurchn/react-native-tinder-clone#1]
Hi. i edit your project to support latest react-native and react-native-navigation[v2], because [v1] is deprecated now.
https://github.com/ZeroCool00/react-native-tinder-theme

i don't know this is the right choice to do, so can i use your project this way.

**Comment by ozgurchn** [comment]
Sure you can =) Also feel free to send any pr along the way

**Comment by ZeroCool00** [comment]
Thank you so much..
